apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bluecompute-application
  namespace: bluecompute
spec:
  selector:
    matchLabels:
      purpose: bluecompute
  componentKinds:
  - group: app.ibm.com
    kind: Subscription
